### ISSUE TITLE
Make your own Mafia/Gang

### ISSUE THREAD

**Issue by ZxBabaxZ** [DeathByKorea/BrokeProtocol#203] opened 2017-08-16 01:50 UTC
I'm spanish and i dont speak too english, sorry for that.

My idea is can creating your own mafia/gang/clan where you can invite people, NPCs, have a Mafia Base and Mafia Cars, but is esencial to the rol playing

**Comment by DeathByKorea** [comment] 2017-08-16 01:51
Duplicate of #11

**Closed by DeathByKorea** 2017-08-16 01:51 UTC
Labels: enhancement
