### ISSUE TITLE
Automaticly reloads when switching weapons.

### ISSUE THREAD

**Issue by UserR00T** [DeathByKorea/BrokeProtocol#206] opened 2017-08-16 18:24 UTC
When holding glock for example and shooting some bullets, going to another weapon like cuffs and going back reloads the weapon, which is faster than just normally reloading

proof: https://puu.sh/xbHd4/2be6d2cdc5.mp4

**Comment by DeathByKorea** [comment] 2017-08-27 13:12
Duplicate of #69

**Closed by DeathByKorea** 2017-08-27 13:12 UTC
Labels: bug, Client, Minor
