### ISSUE TITLE
Cannot re-position furniture, you must have money >= cost of the item

### ISSUE THREAD

**Issue by cliff7422** [DeathByKorea/BrokeProtocol#122] opened 2017-07-16 23:39 UTC
When you buy furniture, the cost is deducted from your inventory, and then you can place it. However, if you do not have enough money equal to the cost of the furniture at the time of placing it, it will not be placed and you will get the message "Not enough money". This also occurs if you try to re-position furniture and don't have as much money as the furniture costs.

Tested offline, version 0.66 test 3. I also saw this bug briefly on the test 3 server before it went down, didn't get a chance to test it.

**Comment by cliff7422** [comment] 2017-07-16 23:59
Sorry if I wasn't clear, this is a bug, not an enhancement.

**Comment by BrokeProtocol** [comment] 2017-07-17 02:34
Not a bug.

**Comment by BrokeProtocol** [comment] 2017-07-17 03:03
https://my.mixtape.moe/xnvsen.mp4 - not being able to buy furniture is not a bug.

**Comment by BrokeProtocol** [comment] 2017-07-17 12:31
Fixed with test version 6.

**Closed by BrokeProtocol** 2017-07-17 12:31 UTC
Labels: BETA, bug, Client
