### ISSUE TITLE
Accidentally selling apartment (with all my items inside gone now)

### ISSUE THREAD

**Issue by stabbykat** [DeathByKorea/BrokeProtocol#364] opened 2018-01-13 01:08 UTC
I just accidentally sold my apartment where I stored all my money and a ton of weapons and collected items because it is one simple mouse wheel scroll away from entering it for some reason. And there is no check whatsoever for items you have in there that you should have to collect first, like with chests?

**Comment by TheReaperG** [comment] 2018-01-13 03:46
You can't accidentally sell your apartment. In order to do that, you'll have to type /confirm in chat after pressing Sell.

**Comment by stabbykat** [comment] 2018-01-13 05:08
I remember doing that before, but it either is not stock functionality or has been removed as of the recent updates. And haven't replaced it with any other similar security check. You can test this out yourself.

**Comment by TheReaperG** [comment] 2018-01-13 07:38
I’ve deleted my apartment multiple times in v0.72, and it has asked me to do /confirm every single time.

**Comment by UserR00T** [comment] 2018-01-13 13:27
@TheReaperG That ``/confirm`` stuff is part of BP:Essentials, not in the base game.
And this is a duplicate of #163

**Closed by UserR00T** 2018-01-13 13:27 UTC
