### ISSUE TITLE
safehouse bug

### ISSUE THREAD

**Issue by CaNaRdLaK3** [DeathByKorea/BrokeProtocol#175] opened 2017-07-25 17:52 UTC
Please guy i don't know why i lose life in my safehouse.
And if you go back when you enter in your safehouse, you fall and lose life too. 

(sorry for my bad english)

**Comment by iTzTati** [comment] 2017-08-04 01:17
Same thing happened to me in the 10k house.

**Comment by UserR00T** [comment] 2017-11-18 10:53
Dupe of #140 .

**Closed by UserR00T** 2017-11-18 10:53 UTC
Labels: bug, Client, Minor
